#include <Exception.h>

Exception::Exception(void) {
  std::cout << "Hello world desde Exception!" << std::endl;
}